# apiVersion: v1
# kind: ConfigMap
# metadata:
#   labels:
#     app: node-env
#   name: node-env
# data:
#   NODE_ENV: production
# 
# ---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bar-team
  name: bar-team
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bar-team
  template:
    metadata:
      labels:
        app: bar-team
    spec:
      containers:
      # - env:
      #   - name: NODE_ENV
      #     valueFrom:
      #       configMapKeyRef:
      #         key: NODE_ENV
      #         name: node-env
      - name: bar-team
        image: bar-team:1.0
        ports:
        - containerPort: 3002
        resources: {}